packages:
  - 'build'
  - 'build/vite'
  - 'extensions'
  - 'extensions/configuration-editing'
  - 'extensions/css-language-features'
  - 'extensions/css-language-features/server'
  - 'extensions/debug-auto-launch'
  - 'extensions/debug-server-ready'
  - 'extensions/emmet'
  - 'extensions/extension-editing'
  - 'extensions/git'
  - 'extensions/git-base'
  - 'extensions/github'
  - 'extensions/github-authentication'
  - 'extensions/grunt'
  - 'extensions/gulp'
  - 'extensions/html-language-features'
  - 'extensions/html-language-features/server'
  - 'extensions/ipynb'
  - 'extensions/jake'
  - 'extensions/json-language-features'
  - 'extensions/json-language-features/server'
  - 'extensions/markdown-language-features'
  - 'extensions/markdown-math'
  - 'extensions/media-preview'
  - 'extensions/merge-conflict'
  - 'extensions/mermaid-chat-features'
  - 'extensions/microsoft-authentication'
  - 'extensions/notebook-renderers'
  - 'extensions/npm'
  - 'extensions/php-language-features'
  - 'extensions/references-view'
  - 'extensions/search-result'
  - 'extensions/simple-browser'
  - 'extensions/tunnel-forwarding'
  - 'extensions/terminal-suggest'
  - 'extensions/typescript-language-features'
  - 'extensions/vscode-api-tests'
  - 'extensions/vscode-colorize-tests'
  - 'extensions/vscode-colorize-perf-tests'
  - 'extensions/vscode-test-resolver'
  - 'remote'
  - 'remote/web'
  - 'test/automation'
  - 'test/integration/browser'
  - 'test/monaco'
  - 'test/smoke'
  - 'test/mcp'
  - '.vscode/extensions/vscode-selfhost-import-aid'
  - '.vscode/extensions/vscode-selfhost-test-provider'
